apiVersion: v1
kind: Service
metadata:
  name: techapp-service
  labels:
    app: mnptech-green
spec:
  selector:
    app: mnptech-green

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
