apiVersion: v1
kind: Service
metadata:
  name: techapp-service
  labels:
    app: mnptech-blue
spec:
  selector:
    app: mnptech-blue

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
